### ISSUE TITLE
Kanban Metrics applied for Scrum Teams

### ISSUE THREAD

**Issue by cifu89** [GarciaInes/Scrum-Mastering#1]
I do believe that we as scrum masters can contribute to the improvement of a Scrum Team by introducing flow metrics within the teams we work with.

I would like to have a section describing the most common metrics that we use and why we use them.

**Comment by GarciaInes** [comment]
Sure thats the Indicators in each ceremony, feel free to add and send over request

**Comment by GarciaInes** [comment]
Not quite aligned had to rework some of the content to fit the structure. Future items to be applied as on folder and file structure
